# Generated by Django 4.2.11 on 2025-08-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Account',
            },
        ),
    ]
