# Generated by Django 4.2.11 on 2025-08-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD')], default='CAD', max_length=3, verbose_name='Currency'),
        ),
        migrations.CreateModel(
            name='AccountTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='folio.account')),
            ],
            options={
                'verbose_name': 'Account Tx',
                'verbose_name_plural': 'Account Tx',
                'ordering': ['-date'],
            },
        ),
    ]
