# Generated by Django 4.2.11 on 2025-08-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_account_balance_account_currency_accounttx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttx',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
