# Generated by Django 4.2.11 on 2025-08-06 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0003_alter_accounttx_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='Symbol')),
                ('name', models.CharField(default='', max_length=256, verbose_name='Name')),
                ('currency', models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD')], default='CAD', max_length=3, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Ticker',
                'verbose_name_plural': 'Ticker',
            },
        ),
        migrations.AddField(
            model_name='accounttx',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance'),
        ),
        migrations.CreateModel(
            name='TradeTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('tx_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend')], default='BUY', max_length=18, verbose_name='Type')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='folio.account')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='folio.ticker')),
            ],
            options={
                'verbose_name': 'Trades',
                'verbose_name_plural': 'Trades',
                'ordering': ['-date'],
            },
        ),
    ]
