# Generated by Django 4.2.11 on 2025-08-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0004_ticker_accounttx_description_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradetx',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='tradetx',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Price'),
        ),
    ]
