# Generated by Django 4.2.11 on 2025-08-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0005_alter_tradetx_amount_alter_tradetx_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='investment',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Investment'),
        ),
        migrations.AddField(
            model_name='account',
            name='position',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='accounttx',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance'),
        ),
    ]
