# Generated by Django 4.2.11 on 2025-08-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0006_account_investment_account_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradetx',
            options={'ordering': ['-date'], 'verbose_name': 'Trade Tx', 'verbose_name_plural': 'Trade Tx'},
        ),
        migrations.AddField(
            model_name='ticker',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, verbose_name='Price'),
        ),
    ]
