# Generated by Django 4.2.11 on 2025-08-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0007_alter_tradetx_options_ticker_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Data'),
        ),
    ]
