# Generated by Django 4.2.11 on 2025-08-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0008_account_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='position',
        ),
    ]
